### ISSUE TITLE
Reboot/Shutdown causes IOException

### ISSUE THREAD

**Issue by Deantwo** [danikf/tik4net#100]
Using the `/system/reboot` or `/system/shutdown` command will cause an IOException. Not sure what would be a good solution to this issue.
```
>/system/reboot
<
<
Exception thrown: 'System.IO.IOException' in tik4net.dll
>/quit
<
<
```

```
System.IO.IOException: Can not read sentence from connection
   at tik4net.Api.ApiConnection.ReadSentence() in GitHub\tik4net\tik4net\Api\ApiConnection.cs:line 364
   at tik4net.Api.ApiConnection.GetOne(String tag) in GitHub\tik4net\tik4net\Api\ApiConnection.cs:line 416
   at tik4net.Api.ApiConnection.<GetAll>d__54.MoveNext() in GitHub\tik4net\tik4net\Api\ApiConnection.cs:line 434
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at tik4net.Api.ApiConnection.CallCommandSync(String[] commandRows) in GitHub\tik4net\tik4net\Api\ApiConnection.cs:line 466
   at tik4net.Api.ApiCommand.ExecuteNonQuery() in GitHub\tik4net\tik4net\Api\ApiCommand.cs:line 264
   at ...
```
**Example code:**
```C#
TikConnection con = ConnectionFactory.OpenConnection(Type.Api, _host, _username, _password);
ITikCommand cmd = conn.CreateCommand("/system/reboot");
System.Diagnostics.Debug.WriteLine("Executing reboot");
cmd.ExecuteNonQuery();
System.Diagnostics.Debug.WriteLine("Reboot executed");
```

**Comment by Deantwo** [comment]
Found a workaround that seems to work ok.
```C#
TikConnection con = ConnectionFactory.OpenConnection(Type.Api, _host, _username, _password);
System.Diagnostics.Debug.WriteLine("Executing reboot");
conn.Connection.CallCommandAsync(new List<string> { "/system/reboot" }, "reboot", null);
System.Diagnostics.Debug.WriteLine("Reboot executed");
```
Basically using the `CallCommandAsync` method directly and setting the callback action to null.
Slightly worried that [ApiConnection.cs#L503](https://github.com/danikf/tik4net/blob/c2d27b4da2b7ce6de98bbb4f61f89a053fe9c372/tik4net/Api/ApiConnection.cs#L503) will result in an infinite loop in the background though.

**Comment by danikf** [comment]
Fixed. The root cause was that after `/system/reboot` (or `/system/shutdown`), RouterOS closes the TCP connection, which propagated as a raw `IOException`.

**Changes:**
- `ExecuteNonQuery` now treats `!fatal` as a successful completion — the command was delivered, the connection closing is expected behaviour
- `GetAll` catches EOF (remote peer closed TCP) and converts it to a synthetic `!fatal` sentence, so all callers handle it uniformly
- Async commands (`LoadAsync`, `ExecuteAsync`) now correctly clear their `IsRunning` state when the connection is lost mid-stream
- `TestBase.RecreateConnection` now retries with a 20s timeout, so tests that run after a reboot wait for the router to come back instead of failing immediately

Thank you for the report and the workaround suggestion!
