### ISSUE TITLE
Unhandled exception. System.IO.IOException: Can not read sentence from connection

### ISSUE THREAD

**Issue by Guillote29** [danikf/tik4net#82]
Hi!

I have an API developed in .net Core 5.0 and under windows environment it works perfectly, but under linux environment, it gives me the following error in connection.open:

Unhandled exception. System.IO.IOException: Can not read sentence from connection
   at tik4net.Api.ApiConnection.ReadSentence()
   at tik4net.Api.ApiConnection.GetOne(String tag)
   at tik4net.Api.ApiConnection.GetAll(String tag)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at tik4net.Api.ApiConnection.CallCommandSync(String[] commandRows)

the connection code is: 

  ITikConnection connection = ConnectionFactory.CreateConnection(TikConnectionType.Api);
  connection.Open(ipHost, hostUser, hostPassword);

what could be happening?
Thanks!

**Comment by danikf** [comment]
Hi!
Firewall? Could you debug it under linux? Or at least, setup full logging (connection events). Response from mikrotik is empty string. So far - no idea why :-)

I personally don't use linux so I can't verify the functionality.

D

**Comment by danikf** [comment]
Sorry for the very long silence. To answer the Linux part first: **there is nothing platform-specific in this path.** The binary API is a plain TCP socket and 4.0 is tested on Windows and Linux in CI. If the identical code works on Windows and not on Linux, the difference is almost always reachability or policy, not the runtime:

* an outbound firewall rule, or a different source address for the Linux host — `/ip/service/print` has an `address=` allow-list, and the Linux box may not be in it;
* the container/host resolving `ipHost` to something else;
* `/ip/service` `api` disabled, or listening on a different port.

The message itself means the byte stream ended before a complete API sentence arrived. Measured against a live RouterOS 7.24 with the current code:

| What is actually wrong | What you get in 4.0 |
|---|---|
| Plain `Api` pointed at the **API-SSL port 8729** | `TikCommandFatalException: connection lost: Connection closed while reading word body.` |
| `ApiSsl` pointed at the **plain port 8728** | `IOException: Received an unexpected EOF or 0 bytes from the transport stream.` |
| Wrong user or password | `TikConnectionLoginException: Cannot log in. invalid user name or password (6)` |
| Nothing listening / firewalled | `SocketException: connection refused` |

In 3.x every one of those produced the single message you pasted, which is why it told you nothing.

4.0 can also dump the wire when the message is not enough: [Communication debugging](https://github.com/danikf/tik4net/wiki/Communication-debugging).

Note that `ConnectionFactory` still works but the entry point in 4.0 is `TikConnectionSetup`, which is also where timeouts and TLS options live:

```csharp
using var connection = new TikConnectionSetup(host, user, password).Create(TikConnectionType.Api);
```

**4.0.0-beta** is on NuGet. Closing as stale — please reopen if it still reproduces on 4.0.
